language: erlang

env:
   - ST=GemStone-2.4.4.1 BASELINE=ZTimestamp LOADS="'ALL'" REPOSITORY="filetree://${TRAVIS_BUILD_DIR}/repository"
   - ST=GemStone-3.1.0.5 BASELINE=ZTimestamp LOADS="'ALL'" REPOSITORY="filetree://${TRAVIS_BUILD_DIR}/repository"

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $PROJECT_HOME/tests/testTravisCI.sh